'use strict';

let payload = null;
let showAllJournals = false;
let sortKey = 'count';
let sortDir = -1; // 1 asc, -1 desc

const $ = id => document.getElementById(id);

document.addEventListener('DOMContentLoaded', () => {
  $('back-btn').addEventListener('click', (e) => { e.preventDefault(); history.back(); });
  $('go-pubmed').addEventListener('click', () => {
    chrome.tabs.create({ url: 'https://pubmed.ncbi.nlm.nih.gov/' });
  });

  chrome.storage.local.get('statsData', (result) => {
    $('loading').style.display = 'none';
    const data = result.statsData;
    if (!data || data.version !== 2) {
      $('no-data').style.display = 'block';
      if (data && data.version !== 2) {
        const p = $('no-data');
        p.innerHTML = '<p>This analysis was generated by an older plugin version. Please run a new analysis from the PubMed results page.</p><button class="btn" id="go-pubmed">Open PubMed</button>';
        $('go-pubmed').addEventListener('click', () => chrome.tabs.create({ url: 'https://pubmed.ncbi.nlm.nih.gov/' }));
      }
      return;
    }
    payload = data;
    renderAll(data);
  });
});

// ---------------------- meta & header ----------------------
function renderHeader(data) {
  const meta = data.meta || {};
  const when = new Date(meta.generatedAt || Date.now());
  $('stats-timestamp').textContent = `Generated at: ${when.toLocaleString('zh-CN')}`;

  let scopeText;
  if (meta.scope === 'search') {
    scopeText = `Scope: WHOLE search results — analyzed ${(meta.analyzedIds || 0).toLocaleString()} of ${(meta.searchCount || 0).toLocaleString()} hits`;
    if (meta.truncated) scopeText += ` (limited to the first ${(meta.searchLimit || meta.limit || 0).toLocaleString()} hits by the analysis-limit setting)`;
  } else {
    scopeText = `Scope: current page only (${meta.pageCount || 0} articles shown; ${meta.analyzed != null ? meta.analyzed : 0} recognized)`;
    if (meta.searchCount != null) scopeText += ` — whole search: ${meta.searchCount.toLocaleString()} hits (use “Analyze all search results” for full stats)`;
  }
  if (meta.unprocessed) scopeText += ` · ${meta.unprocessed} items not yet processed`;
  $('stats-head-sub').textContent = scopeText;

  const parts = [];
  if (meta.term) parts.push(`Query: ${meta.term}`);
  parts.push(`URL: ${meta.url || ''}`);
  $('stats-meta').textContent = parts.join('  ·  ');
}

// ---------------------- distributions ----------------------
function barRow(label, count, total, color) {
  const pct = total > 0 ? Math.round(count / total * 1000) / 10 : 0;
  const bar = document.createElement('div');
  bar.className = 'distribution-bar';
  bar.innerHTML = `
    <span class="label" style="color:${color || '#333'}">${esc(label)}</span>
    <div class="bar-container"><div class="bar" style="width:${pct}%;${color ? 'background-color:' + color : ''}"></div></div>
    <span class="count">${count}</span>
    <span class="pct">${pct}%</span>`;
  return bar;
}

function renderKeyedDist(containerId, dist, keys, colors, total, labelMap) {
  const container = $(containerId);
  container.innerHTML = '';
  keys.forEach(key => {
    const count = dist[key] || 0;
    const label = (labelMap && labelMap[key]) || key;
    container.appendChild(barRow(label, count, total, colors[key] || '#9E9E9E'));
  });
}

function renderYearDist(containerId, dist) {
  const container = $(containerId);
  container.innerHTML = '';
  const years = Object.keys(dist).sort((a, b) => parseInt(b, 10) - parseInt(a, 10));
  if (!years.length) { container.innerHTML = '<p class="empty">No publication year data</p>'; return; }
  const max = Math.max(...years.map(y => dist[y]));
  years.forEach(y => {
    const count = dist[y];
    const bar = document.createElement('div');
    bar.className = 'distribution-bar';
    bar.innerHTML = `
      <span class="label">${y}</span>
      <div class="bar-container"><div class="bar" style="width:${max ? count / max * 100 : 0}%"></div></div>
      <span class="count">${count}</span>`;
    container.appendChild(bar);
  });
}

// ---------------------- summary ----------------------
function renderSummary(data) {
  const s = data.summary;
  $('s-total').textContent = s.total.toLocaleString();
  const meta = data.meta;
  let sub;
  if (meta.scope === 'search') sub = `based on ${(meta.analyzedIds || 0).toLocaleString()} analyzed hits`;
  else sub = `from ${(meta.pageCount || 0)} articles on the page`;
  if (meta.unprocessed) sub += ` (${meta.unprocessed} not processed)`;
  $('s-total-sub').textContent = sub;

  $('s-sci').textContent = s.sci.toLocaleString();
  $('s-abb').textContent = s.abb.toLocaleString();
  $('s-unknown').textContent = s.unknown.toLocaleString();

  $('s-avgif').textContent = fmt(s.avgIF);
  $('s-medianif').textContent = fmt(s.medianIF);
  $('s-avgif-sub').textContent = `n=${s.withIf.toLocaleString()} articles with IF`;
  $('s-medianif-sub').textContent = `min ${s.minYear ?? '–'} / max ${s.maxYear ?? '–'}`;

  const notes = [];
  if (s.total > 0) {
    notes.push(`SCI-listed (JCR/CAS) articles account for ${pct(s.sci, s.total)} of the analyzed set; ${pct(s.unknown, s.total)} could not be matched to the journal database.`);
    if (s.withIf > 0) notes.push(`Mean and median IF are computed over the ${s.withIf.toLocaleString()} articles that carry a numeric journal IF.`);
    if (meta.unprocessed) notes.push(`⚠ ${meta.unprocessed} item(s) on the page had not finished journal recognition when analysis ran — rerun or use “Analyze all search results” for complete figures.`);
    if (meta.truncated) notes.push(`⚠ The full search contained ${(meta.searchCount || 0).toLocaleString()} results, but this analysis only covered the first ${(meta.searchLimit || meta.limit || 0).toLocaleString()} (analysis-limit setting in the extension popup).`);
  }
  $('summary-note').textContent = notes.join(' ');
}

// ---------------------- tables ----------------------
function journalRowHtml(j, idx, showRank) {
  const pubLink = `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent('"' + j.name + '"[Journal]')}`;
  const jcrCls = ['Q1', 'Q2', 'Q3', 'Q4'].includes(j.jcr) ? j.jcr.toLowerCase() : 'na';
  const casCls = ['B1', 'B2', 'B3', 'B4'].includes(j.cas) ? j.cas.toLowerCase() : 'na';
  const oaBadge = j.oa === 'OA' ? '<span class="badge badge-oa">OA</span>' : (j.oa === 'Non-OA' ? '<span class="badge badge-non">Non-OA</span>' : '<span class="badge badge-unk">?</span>');
  return `
    <tr>
      ${showRank ? `<td class="rank">${idx + 1}</td>` : ''}
      <td><a class="jm-link" href="${esc(pubLink)}" target="_blank" rel="noopener noreferrer">${esc(j.name)}</a></td>
      <td>${j.count}</td>
      <td>${j.ifAvg != null ? fmt(j.ifAvg) : '–'}</td>
      <td><span class="${jcrCls}">${esc(j.jcr || 'NA')}</span></td>
      <td><span class="${casCls}">${esc(j.cas || 'NA')}</span></td>
      <td>${j.top ? '<span class="badge badge-top">TOP</span>' : ''}</td>
      <td>${oaBadge}${j.oa && j.oa !== 'Unknown' ? '' : ''}</td>
      <td>${j.apc != null ? j.apc : '–'}</td>
      <td>${esc(j.publisher || '–')}</td>
      <td>${esc(j.country || '–')}</td>
    </tr>`;
}

function renderJournalTable() {
  const tbody = $('journal-tbody');
  tbody.innerHTML = '';
  const rows = payload.journals || [];
  if (!rows.length) {
    $('journal-tbody').innerHTML = '<tr><td colspan="11" class="empty">No SCI-listed journals found in this result set.</td></tr>';
    $('journal-count-note').textContent = '';
    return;
  }
  const sorted = rows.slice().sort((a, b) => {
    let va = a[sortKey], vb = b[sortKey];
    if (sortKey === 'name') { va = String(va || '').toLowerCase(); vb = String(vb || '').toLowerCase(); }
    else { va = va == null ? -1 : va; vb = vb == null ? -1 : vb; }
    if (va < vb) return -sortDir;
    if (va > vb) return sortDir;
    return b.count - a.count;
  });
  const limit = showAllJournals ? 1000 : 15;
  const visible = sorted.slice(0, limit);
  visible.forEach((j, i) => {
    tbody.insertAdjacentHTML('beforeend', journalRowHtml(j, i, true));
  });
  const truncatedCount = sorted.length - visible.length;
  $('journal-count-note').textContent = `${rows.length} distinct SCI journals · showing ${visible.length}${truncatedCount > 0 ? ` (${truncatedCount} more available in CSV export)` : ''}`;
  $('toggle-all-journals').textContent = showAllJournals ? 'Show top 15' : 'Show all journals';
  $('toggle-all-journals').disabled = rows.length <= 15 && !showAllJournals;
}

function renderList(listEl, items, withLink) {
  const el = $(listEl);
  el.innerHTML = '';
  if (!items || !items.length) { el.innerHTML = '<p class="empty">None — great coverage!</p>'; return; }
  items.slice(0, 200).forEach(it => {
    const link = withLink
      ? `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent('"' + it.name + '"[Journal]')}`
      : '';
    const inner = link ? `<a class="jm-link" href="${esc(link)}" target="_blank" rel="noopener noreferrer">${esc(it.name)}</a>` : esc(it.name);
    const row = document.createElement('div');
    row.className = 'distribution-bar';
    row.innerHTML = `<span class="label" style="width:auto;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding-right:8px;">${inner}</span><span class="count">${it.count}</span>`;
    el.appendChild(row);
  });
  if (items.length > 200) el.insertAdjacentHTML('beforeend', `<p class="empty">… ${items.length - 200} more (full list in CSV where applicable)</p>`);
}

// ---------------------- actions ----------------------
function buildSummaryText(lang) {
  const s = payload.summary;
  const meta = payload.meta;
  const journals = (payload.journals || []).slice(0, 5);
  const L = [];
  if (lang === 'zh') {
    L.push('【JournalMetrics 检索结果分析摘要】');
    L.push(`分析范围: ${meta.scope === 'search' ? '整次检索结果' : '当前页面'}`);
    if (meta.term) L.push(`检索式: ${meta.term}`);
    if (meta.scope === 'search') L.push(`检索命中 ${(meta.searchCount || 0).toLocaleString()} 条；已分析 ${(meta.analyzedIds || 0).toLocaleString()} 条${meta.truncated ? `（按设置仅分析前 ${(meta.searchLimit || meta.limit || 0).toLocaleString()} 条）` : ''}`);
    else L.push(`当前页面 ${meta.pageCount || 0} 条${meta.unprocessed ? `（${meta.unprocessed} 条未完成识别）` : ''}`);
    L.push(`共分析 ${s.total} 条：SCI 期刊（有 IF/JCR 数据）${s.sci} 条，其他已识别期刊 ${s.abb} 条，未能识别 ${s.unknown} 条；`);
    if (s.withIf > 0) L.push(`其中有 IF 数值的 ${s.withIf} 条：平均 IF ${fmt(s.avgIF)}，中位 IF ${fmt(s.medianIF)}${s.minYear && s.maxYear ? `（年份 ${s.minYear}–${s.maxYear}）` : ''}；`);
    const q = payload.dists.jcrDist;
    if (s.sci > 0) L.push(`JCR 分区：Q1 ${q.Q1}（${pct(q.Q1, s.sci)}）、Q2 ${q.Q2}（${pct(q.Q2, s.sci)}）、Q3 ${q.Q3}（${pct(q.Q3, s.sci)}）、Q4 ${q.Q4}（${pct(q.Q4, s.sci)}）；`);
    if (journals.length) L.push('发文量 Top 期刊：' + journals.map((j, i) => `${i + 1}.${j.name}（${j.count} 篇${j.ifAvg != null ? `, 均IF ${fmt(j.ifAvg)}` : ''}）`).join('；') + '。');
    L.push(`未识别期刊 ${s.unknown} 条，如需完善数据可反馈列表。`);
  } else {
    L.push('JournalMetrics analysis summary');
    L.push(`Scope: ${meta.scope === 'search' ? 'whole search results' : 'current page only'}`);
    if (meta.term) L.push(`Query: ${meta.term}`);
    if (meta.scope === 'search') L.push(`Search hits: ${(meta.searchCount || 0).toLocaleString()} — analyzed ${(meta.analyzedIds || 0).toLocaleString()}${meta.truncated ? ` (limited to first ${(meta.searchLimit || meta.limit || 0).toLocaleString()} by the analysis-limit setting)` : ''}`);
    else L.push(`Page articles: ${meta.pageCount || 0}${meta.unprocessed ? ` (${meta.unprocessed} not yet processed)` : ''}`);
    L.push(`Analyzed ${s.total} articles: ${s.sci} from SCI-listed journals, ${s.abb} other known journals, ${s.unknown} unrecognized.`);
    if (s.withIf > 0) L.push(`Mean IF ${fmt(s.avgIF)} / median IF ${fmt(s.medianIF)} (n=${s.withIf}, numeric IF). Years ${s.minYear ?? '?'}–${s.maxYear ?? '?'}.`);
    const q = payload.dists.jcrDist;
    if (s.sci > 0) L.push(`JCR quartiles: Q1 ${q.Q1} (${pct(q.Q1, s.sci)}%), Q2 ${q.Q2}, Q3 ${q.Q3}, Q4 ${q.Q4}.`);
    if (journals.length) L.push('Top journals by article count: ' + journals.map((j, i) => `${i + 1}. ${j.name} (${j.count}; avg IF ${j.ifAvg != null ? fmt(j.ifAvg) : 'n/a'})`).join('; ') + '.');
  }
  return L.join('\n');
}

function copyText(text) {
  return navigator.clipboard.writeText(text).then(() => true, () => false);
}

function csvCell(v) {
  const s = String(v == null ? '' : v);
  return '"' + s.replace(/"/g, '""') + '"';
}

function exportCSV() {
  const journals = payload.journals || [];
  const header = ['Journal', 'Articles', 'AvgIF', 'JCR', 'CAS', 'Top', 'OA', 'APC(USD)', 'Publisher', 'Country', 'Website'];
  const lines = [header.map(csvCell).join(',')];
  journals.forEach(j => {
    lines.push([
      j.name, j.count,
      j.ifAvg != null ? fmt(j.ifAvg) : '',
      j.jcr || '', j.cas || '', j.top ? 'TOP' : '',
      j.oa || '', j.apc != null ? j.apc : '',
      j.publisher || '', j.country || '', j.website || ''
    ].map(csvCell).join(','));
  });
  // unrecognized journals too, marked
  if (payload.unmatched && payload.unmatched.length) {
    lines.push(csvCell('— unrecognized journals (not in database) —'));
    payload.unmatched.forEach(u => lines.push([u.name, u.count, '', '', '', '', '', '', '', '', ''].map(csvCell).join(',')));
  }
  const blob = new Blob(['\ufeff' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `journalmetrics_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(a.href);
}

async function runCopy(lang) {
  const ok = await copyText(buildSummaryText(lang));
  if (ok) { /* optionally toast */ } else {
    // fallback for older contexts
    const ta = document.createElement('textarea');
    ta.value = buildSummaryText(lang);
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand('copy'); } catch (e) { /* ignore */ }
    ta.remove();
  }
}

// ---------------------- helpers ----------------------
function fmt(v) {
  const n = parseFloat(v);
  if (isNaN(n)) return '0.0';
  return Math.round(n * 100) / 100;
}
function pct(a, b) { return b > 0 ? Math.round(a / b * 1000) / 10 : 0; }
function esc(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function renderAll(data) {
  renderHeader(data);
  renderSummary(data);

  const s = data.summary;
  const d = data.dists;

  renderKeyedDist('jcr-distribution', d.jcrDist, ['Q1', 'Q2', 'Q3', 'Q4', 'NA'],
    { Q1: '#4CAF50', Q2: '#2196F3', Q3: '#FF9800', Q4: '#F44336', NA: '#9E9E9E' }, s.sci);
  renderKeyedDist('cas-distribution', d.casDist, ['B1', 'B2', 'B3', 'B4', 'NA'],
    { B1: '#E91E63', B2: '#9C27B0', B3: '#673AB7', B4: '#3F51B5', NA: '#9E9E9E' }, s.sci);

  // discipline
  const clsEl = $('cls-distribution');
  clsEl.innerHTML = '';
  $('cls-note').textContent = `based on ${s.sci} SCI-listed articles`;
  if (!d.clsDist || !d.clsDist.length) clsEl.innerHTML = '<p class="empty">No discipline data</p>';
  else d.clsDist.forEach((c, i) => clsEl.appendChild(barRow(c.label, c.count, s.sci, undefined)));

  // OA
  const oaTotal = (d.oaDist.oa || 0) + (d.oaDist.non || 0) + (d.oaDist.unknown || 0);
  renderKeyedDist('oa-distribution', d.oaDist, ['oa', 'non', 'unknown'],
    { oa: '#4CAF50', non: '#9E9E9E', unknown: '#90a4ae' }, oaTotal,
    { oa: 'Open Access', non: 'Non-OA', unknown: 'Unknown' });

  renderYearDist('year-distribution', d.yearDist);

  renderKeyedDist('if-distribution', d.ifDist, ['<1', '1-3', '3-5', '5-10', '10-20', '>=20'],
    { '<1': '#9E9E9E', '1-3': '#4fc3f7', '3-5': '#1a73e8', '5-10': '#3949ab', '10-20': '#7b1fa2', '>=20': '#c2185b' },
    s.withIf);

  renderJournalTable();
  renderList('unmatched-list', data.unmatched, true);
  renderList('other-list', data.others, true);

  // actions wiring
  $('copy-summary-en').addEventListener('click', () => runCopy('en'));
  $('copy-summary-zh').addEventListener('click', () => runCopy('zh'));
  $('export-csv').addEventListener('click', exportCSV);
  $('toggle-all-journals').addEventListener('click', () => {
    showAllJournals = !showAllJournals;
    renderJournalTable();
  });

  document.querySelectorAll('#journal-table th[data-key]').forEach(th => {
    th.addEventListener('click', () => {
      const key = th.dataset.key;
      if (key === 'rank') return;
      if (sortKey === key) sortDir = -sortDir;
      else { sortKey = key; sortDir = key === 'name' ? 1 : -1; }
      renderJournalTable();
    });
  });

  $('content').style.display = 'block';
}
